### ISSUE TITLE
Include XML documentation file in all packages

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-csharp#426]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Motivation

XML documentation file is used by IDEs for autocompletion and API discovery.

#### Packages

```[tasklist]
### Tasks
- [ ] XML documentation for Allure.Net.Commons
- [ ] XML documentation for Allure.NUnit
- [ ] XML documentation for Allure.SpecFlow
- [ ] XML documentation for Allure.XUnit
```
